config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users

  resources :users, only: [:show]
  resources :activities, except: [:edit] do
    member do
      get 'listing'
      get 'details'
      get 'photos'
      get 'location'
      get 'price'
    end
  end

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  has_many_attached :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :fullname, presence: true, length: {maximum: 15}

  has_many :activities
end

app/controllers/activities_controller.rb
 class ActivitiesController < ApplicationController
  before_action :set_activity, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]

  def index
    @activities = current_user.activities
  end

  def new
    @activity = current_user.activities.build
  end

  def create
    @activity = current_user.activities.build(activity_params)
    if @activity.save
      redirect_to details_activity_path(@activity), notice: "Saved.."
    else
      flash[:alert] = "Something is wrong.."
      render :new
    end
  end

  def update
    if @activity.update(activity_params)
      flash[:notice] = "Updated successfully.."
    else
      flash[:notice] = "Something is wrong.."
    end
    redirect_back(fallback_location: request.referer)
  end

  def listing
  end

  def show
  end

  def details
  end

  def photos
  end

  def location
  end

  def price
  end

  private
    def set_activity
      @activity = Activity.find(params[:id])
    end

    def activity_params
      params.require(:activity).permit(:name, :about, :details_1, :details_2, :how_to_directions, :how_to_seats, :activity_info, :refund_policies, :location_map, :location_title, :base_price, :adult_price, :child_price, :my_adult_price, :my_child_price, :int_adult_price, :int_child_price, :is_base_price, :is_adult, :is_child, :is_my_adult, :is_my_child, :is_int_adult, :is_int_child, images: [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:fullname])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&s=150"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/activities/_create_activity_menu.html.erb
<div class="card-content">
    <h4 class="center">Please fill all the required information</h4>
</div><!-- card-content -->
<br/>
<div class="card-tabs">
    <ul class="tabs tabs-fixed-width">
        <li class="tab"><%= link_to "Details", details_activity_path %></li>
        <li class="tab"><%= link_to "Photos", photos_activity_path %></li>
        <li class="tab"><%= link_to "Locations", location_activity_path %></li>
        <li class="tab"><%= link_to "Pricing", price_activity_path %></li>
    </ul><!-- tabs -->
</div><!-- card-tabs -->

app/views/activities/create.html.erb
<h1>Activities#create</h1>
<p>Find me in app/views/activities/create.html.erb</p>

app/views/activities/details.html.erb
<!-- Create Package Section -->
<div class="row">
  <div class="col s12">

    <div class="card-panel">

      <%= render 'create_activity_menu' %>

      <div class="card-content">
          <div id="details">
              <div class="row">
                <h5 class="center">Activity Details Section</h5>
                  <%= form_for @activity, class: "col s12" do |f| %>
                      <div class="row">
                        <div class="input-field col s12">
                          <%= f.text_area :about, id: "about-text", class: "materialize-textarea" %>
                          <label for="about-text">About</label>
                          <span class="helper-text">Enter an introduction about this activity</span>
                        </div><!-- input-field -->
                      </div><!-- row -->
                      <div class="row">
                        <div class="input-field col s12">
                          <%= f.text_area :details_1, id: "details-text-1", class: "materialize-textarea" %>
                          <label for="details-text-1">Information About Details 1</label>
                          <span class="helper-text">Enter important information about this activity</span>
                        </div><!-- input-field -->
                      </div><!-- row -->
                      <div class="row">
                        <h6>Detail 2 will add more information, leave blank if there is no more information.</h6>
                        <div class="input-field col s12">
                          <%= f.text_area :details_2, id: "details-text-2", class: "materialize-textarea" %>
                          <label for="detail-text-2">Information About Details 2</label>
                          <span class="helper-text">Add more information about activity.</span>
                        </div><!-- input-field -->
                      </div><!-- row -->
                      <br/>
                      <br/>
                      <hr/>
                      <br/>
                      <br/>
                      <div class="row">
                        <h6>How to get there</h6>
                        <div class="input-field col s12">
                          <%= f.text_area :how_to_directions, id: "direction-text", class: "materialize-textarea" %>
                          <label for="direction-text">Directions Text</label>
                          <span class="helper-text">Enter text information on how to get to location.</span>
                        </div><!-- input-field -->
                      </div><!-- row -->
                      <div class="row">
                        <h6>How to secure your seats</h6>
                        <div class="input-field col s12">
                          <%= f.text_area :how_to_seats, id: "secure-seats-text", class: "materialize-textarea" %>
                          <label for="secure-seats-text">Secure Seats</label>
                          <span class="helper-text">Enter text information on how to secure seats.</span>
                        </div><!-- input-field -->
                      </div><!-- row -->
                      <div class="row">
                        <h6>Additional Information</h6>
                        <div class="input-field col s12">
                          <%= f.text_area :activity_info, id: "add-information-text", class: "materialize-textarea" %>
                          <label for="add-information-text">Additional Information</label>
                          <span class="helper-text">Add more information about this reservation, leave blank if not required.</span>
                        </div><!-- input-field -->
                      </div><!-- row -->
                      <div class="row">
                        <h6>Cancellation &amp; Refund Policies</h6>
                        <div class="input-field col s12">
                          <%= f.text_area :refund_policies, id: "refund-policies-text", class: "materialize-textarea" %>
                          <label for="refund-policies-text">Cancellation &amp; Refund Policies</label>
                          <span class="helper-text">Add cancellation &amp; refund policies for this activity.</span>
                        </div><!-- input-field -->
                      </div><!-- row -->

                      <div class="row">
                        <div class="col s12">
                          <%= button_tag type: "submit", class: "btn waves-effect waves-light", name: "action" do %>
                            Update<span><i class="material-icons right">update</i></span>
                          <% end %>
                        </div><!-- col -->
                      </div><!-- row -->

                  <% end %>
              </div><!-- row -->
          </div><!-- details -->

      </div><!-- card-content -->
    </div><!-- card-panel -->
  </div><!-- col -->
</div><!-- row -->

app/views/activities/index.html.erb
<h1>Activities#index</h1>
<p>Find me in app/views/activities/index.html.erb</p>

app/views/activities/location.html.erb
<!-- Create Package Section -->
<div class="row">
  <div class="col s12">
    <div class="card-panel">

      <%= render 'create_activity_menu' %>

      <div class="card-content">
          <div id="location">
            <div class="row">
              <h5 class="center">Location Title and Google Map</h5>
                <%= form_for @activity, class: "col s12" do |f| %>
                  <div class="row">
                    <div class="input-field col s12">
                      <%= f.text_field :location_title, id: "location-title", type: "text" %>
                      <label for="location-title">Location Title</label>
                      <span class="helper-text">Location title will be displayed as a text.</span>
                    </div><!-- input-field -->
                  </div><!-- row -->
                  <br/>
                  <br/>
                  <div class="row">
                    <div class="input-field col s12">
                      <%= f.text_field :location_map, id: "location-map", type: "text" %>
                      <label for="location-map">Location on Google Map</label>
                      <span class="helper-text">Type a location name in Google Map, will be displayed as a Google Map</span>
                    </div><!-- input-field -->
                  </div><!-- row -->

                  <div class="row">
                    <div class="col s12">
                      <%= button_tag type: "submit", class: "btn waves-effect waves-light", name: "action" do %>
                        Update<span><i class="material-icons right">update</i></span>
                      <% end %>
                    </div><!-- col -->
                  </div><!-- row -->

                <% end %>
            </div><!-- row -->
        </div><!-- location -->

      </div><!-- card-content -->
    </div><!-- card-panel -->
  </div><!-- col -->
</div><!-- row -->

app/views/activities/new.html.erb
<!-- START CREATE ACTIVITY PAGE -->
<div class="row">
  <div class="col s12">

    <div class="card-panel">
      <div class="card-content">
        <h5 class="center">Create your new activity</h5>
        <p class="center">Please enter activity name and select the price category for your activity</p>
      </div><!-- card-content -->
      <div class="card-content">
        <div class="row">
          <%= form_for @activity, class: "col s12" do |f| %>
            <div class="input-field col s12">
              <%= f.text_field :name, id: "activity-name", type: "text" %>
              <label for="activity-name">Activity Name</label>
            </div><!-- input-field -->

            <div><%= f.submit "Create", class: "btn waves-effect waves-light" %></div>

          <% end %>
        </div><!-- row -->

      </div><!-- card-content -->



    </div><!-- card-panel -->

  </div><!-- col -->
</div><!-- row -->

app/views/activities/photos.html.erb
<!-- Create Package Section -->
<div class="row">
  <div class="col s12">

    <div class="card-panel">

      <%= render 'create_activity_menu' %>

      <div class="card-content">
        <!-- PHOTOS UPLOAD SECTION IS NOT YET COMPLETE -->
          <div id="photos">
            <%= form_for @activity do |f| %>
              <h5 class="center">Upload photos for slider and banner</h5>
              <br/>
              <br/>
              <br/>
              <p>First photo will be used as banner image, upload multiple to make a photo slider.</p>
              <div class="file-field input-field">
                <div class="btn">
                    <span>Upload</span>
                    <!-- <input type="file" multiple> -->
                    <%= f.file_field :images, type: "file", multiple: true %>
                </div><!-- btn -->
                <div class="file-path-wrapper">
                    <!-- <input class="file-path validate" type="text" placeholder="Upload one or more photos"> -->
                    <%= f.text_field :images, class: "file-path validate", type: "text", placeholder: "Upload one or more photos" %>
                </div><!-- file-path-wrapper -->
              </div><!-- file input-field -->

              <div class="row">
                <div class="col s12">
                  <%= button_tag type: "submit", class: "btn waves-effect waves-light", name: "action" do %>
                    Update<span><i class="material-icons right">update</i></span>
                  <% end %>
                </div><!-- col -->
              </div><!-- row -->

            <% end %>
          </div><!-- photos -->

      </div><!-- card-content -->
    </div><!-- card-panel -->
  </div><!-- col -->
</div><!-- row -->

app/views/activities/price.html.erb
<!-- Create Package Section -->
<div class="row">
  <div class="col s12">

    <div class="card-panel">

      <%= render 'create_activity_menu' %>

      <div class="card-content">
        <div id="price">
          <div class="row">
            <h5 class="center">Pricing</h5>
              <%= form_for @activity, class: "col s12" do |f| %>
                  <div class="row">
                    <h6>Base Price</h6>
                    <div class="input-field col s12">
                      <%= f.text_field :base_price, id: "base-price", type: "number", value: "0" %>
                      <label for="base-price">Base Price</label>
                      <span class="helper-text">Base price will be charged if there are no addon prices eg: adult, child etc. Leave it as '0' if required to choose addon.</span>
                    </div><!-- input-field -->
                  </div><!-- row -->
                  <br/>
                  <br/>
                  <hr/>
                  <br/>
                  <br/>
                  <h5 class="center">For price that doesn't require IC/Passport, use this</h5>
                  <br/>
                  <div class="row">
                    <h6>Adult</h6>
                    <div class="input-field col s12">
                      <%= f.text_field :adult_price, id: "adult" %>
                      <label for="my-adult">Adult</label>
                      <span class="helper-text">Addon price for adult</span>
                    </div><!-- input-field -->
                  </div><!-- row -->
                  <div class="row">
                    <h6>Child</h6>
                    <div class="input-field col s12">
                      <%= f.text_field :child_price, id: "child", type: "number" %>
                      <label for="child">Child</label>
                      <span class="helper-text">Addon price for child</span>
                    </div><!-- input-field -->
                  </div><!-- row -->
                  <br/>
                  <br/>
                  <hr/>
                  <br/>
                  <br/>
                  <h5 class="center">For price that require IC/Passport, use this instead</h5>
                  <br/>
                  <div class="row">
                    <h6>Malaysian, adult</h6>
                    <div class="input-field col s12">
                      <%= f.text_field :my_adult_price, id: "my-adult", type: "number" %>
                      <label for="my-adult">Malaysian adult</label>
                      <span class="helper-text">Addon price for MY adult</span>
                    </div><!-- input-field -->
                  </div><!-- row -->
                  <div class="row">
                    <h6>Malaysian, child</h6>
                    <div class="input-field col s12">
                      <%= f.text_field :my_child_price, id: "my-child", type: "number" %>
                      <label for="my-child">Malaysian child</label>
                      <span class="helper-text">Addon price for MY child</span>
                    </div><!-- input-field -->
                  </div><!-- row -->
                  <div class="row">
                    <h6>International, adult</h6>
                    <div class="input-field col s12">
                      <%= f.text_field :int_adult_price, id: "int-adult", type: "number" %>
                      <label for="int-adult">International adult</label>
                      <span class="helper-text">Addon price for international adult</span>
                    </div><!-- input-field -->
                  </div><!-- row -->
                  <div class="row">
                    <h6>International, child</h6>
                    <div class="input-field col s12">
                      <%= f.text_field :int_child_price, id: "int-child", type: "number" %>
                      <label for="int-child">International child</label>
                      <span class="helper-text">Addon price for International child</span>
                    </div><!-- input-field -->
                  </div><!-- row -->

                  <div class="row">
                    <div class="col s12">
                      <%= button_tag type: "submit", class: "btn waves-effect waves-light", name: "action" do %>
                        Update<span><i class="material-icons right">update</i></span>
                      <% end %>
                    </div><!-- col -->
                  </div><!-- row -->

              <% end %>
          </div><!-- row -->
        </div><!-- price -->

      </div><!-- card-content -->
    </div><!-- card-panel -->
  </div><!-- col -->
</div><!-- row -->

app/views/activities/show.html.erb
<h1>Activities#show</h1>
<p>Find me in app/views/activities/show.html.erb</p>

app/views/activities/update.html.erb
<h1>Activities#update</h1>
<p>Find me in app/views/activities/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuyTickets.my | Langkawi Island | Mangrove Tour | Cable Car | Xtreme Park | Skytrex Langkawi | Langkawi Popular Activities</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/message'%>

    <div class="container">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer grey darken-3">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">About Us</h5>
          <p class="grey-text text-lighten-4">
              We at <%= link_to 'BuyTickets', 'https://buytickets.my' %> keep our customers experience at the top of our priority!
              Offering only the best things that we ourselves believe better than any other place you'd pay for your vacation.
              Leave all the hassle to look for affordable price to us, we are really good at it.
          </p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Featured</h5>
          <ul>
            <li><a class="white-text" href="#!">Mangrove Tour</a></li>
            <li><a class="white-text" href="#!">Island Hopping</a></li>
            <li><a class="white-text" href="#!">Car Rental</a></li>
            <li><a class="white-text" href="#!">Honeymoon Packages</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><%= link_to 'Login', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'BuyTickets.my', 'https://www.facebook.com/buyticketsmy' %></li>
            <li><%= link_to 'Instagram', 'https://www.instagram.com' %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright grey darken-4">
      <div class="container">
      &copy; 2017 - 2018 <%= link_to 'BuyTickets.my', 'https://www.facebook.com/buyticketsmy' %>
      </div>
    </div>
  </footer>


    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
    <script>
        $(document).ready(function () {

            //Initiate Slider
            /* global $ */
            $('.slider').slider({
               indicators: false,
               height: 500,
               transition: 500,
               interval: 6000
            });

            //Initiate Dropdown
            $(".dropdown-trigger").dropdown();

            //Initiate Sidenav
            $('.sidenav').sidenav({
              edge: 'right'
            });


        });
    </script>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Dropdown Desktop -->
<ul id="dropdown-lg" class="dropdown-content">
  <li><%= link_to 'Profile', edit_user_registration_path %></li>
  <li><a href="#">Reservation</a></li>
  <li><%= link_to 'LOGOUT', destroy_user_session_path, method: :delete %></li>
</ul>
<!-- Sidenav Menu -->
<ul id="mobile-menu" class="sidenav">
  <li><%= link_to 'Profile', edit_user_registration_path %></li>
  <li><a href="#">Reservation</a></li>
  <li><%= link_to 'LOGOUT', destroy_user_session_path, method: :delete %></li>
</ul>
<div class="navbar-fixed">
    <nav class="grey lighten-5">
        <div class="container">
            <div class="nav-wrapper">
                <%= link_to image_tag('weblogo/main-logo-web.png', class: 'img-logo'), root_path, class: 'brand-logo' %>
                <ul class="right hide-on-med-and-down">
                    <li><a href="popular.html">Popular Activities</a></li>
                    <li><a href="packages.html">Packages</a></li>
                    <li><a href="contact.html">Contact Us</a></li>
                    <% if (!user_signed_in?) %>
                      <li><%= link_to 'LOGIN', new_user_session_path, class: 'waves-effect waves-light btn-small red white-text' %></li>
                    <% else %>
                      <li>
                        <a class="dropdown-trigger" href="#!" data-target="dropdown-lg">
                          <%= current_user.fullname %><i class="material-icons right">arrow_drop_down</i></a>
                      </li>
                    <% end %>

                    <!-- Please add a clickable icons -->

                    <!-- <li><a href="https://www.facebook.com/buyticketsmy"><i class="fab fa-facebook"></i></a></li> -->
                    <!-- <li><a href="https://www.instagram.com"><i class="fab fa-instagram"></i></a></li> -->
                </ul>
            </div><!-- nav-wrapper -->
        </div><!-- container -->
    </nav>
</div><!-- navbar-fixed -->

<!-- Mobile Nav -->
<div class="mobile-nav hide-on-large-only center">
    <div class="container">
        <div class="row">
            <div class="col s3">
                <a href="popular.html" class="waves-effect waves-light btn-flat">Popular Activities</a>
            </div>
            <div class="col s3">
                <a href="packages.html" class="waves-effect waves-light btn-flat">Packages</a>
            </div>
            <div class="col s3">
                <a href="#" class="waves-effect waves-light btn-flat">Contact Us</a>
            </div>
            <div class="col s3">
              <% if (!user_signed_in?) %>
                <%= link_to 'LOGIN', new_user_session_path, class: 'waves-effect waves-light btn-small red white-text' %>
              <% else %>
              <a href="#" data-target="mobile-menu" class="sidenav-trigger btn-small btn-flat"><i class="material-icons center">menu</i></a>

              <!-- Try make a button with arrow down icon -->
                <!-- <a class="sidenav-trigger" href="#!" data-target="mobile-menu"><i class="material-icons right">menu</i></a> -->
              <% end %>
            </div>
        </div><!-- row -->
    </div><!-- container -->
</div><!-- mobile-nav -->